export const lancamentosImgLink = [
  {
    id: 1,
    name: "Camisa Fluminense Goleiro 2025 Roxo/Marinho Umbro",
    src: "/lancamentos/camisa-goleiro-roxa-umbro-1.webp",
    price: "R$ 369,99",
    parcel: "ou 6x de R$ 61,66",
  },
  {
    id: 2,
    name: "Calça Fluminense Viagem 2025 Grená/Areia Umbro",
    src: "/lancamentos/calca-viagem-63357-1.webp",
    price: "R$ 299,99",
    parcel: "ou 5x de R$ 59,99",
  },
  {
    id: 3,
    name: "Camisa Fluminense Faixa Verde Foxton",
    src: "/lancamentos/camisa-faixa-verde-64191-1.webp",
    price: "R$ 199,99",
    parcel: "ou 3x de R$ 66,66",
  },
  {
    id: 4,
    name: "Camisa Fluminense Jogador Grená Foxton",
    src: "/lancamentos/camisa-jogador-grena-64193-1.webp",
    price: "R$ 249,99",
    parcel: "ou 4x de R$ 62,49",
  },

  {
    id: 5,
    name: "Camisa Fluminense América do Sul Foxton",
    src: "/lancamentos/camisa-america-do-sul-64187-1.webp",
    price: "R$ 199,99",
    parcel: "ou 3x de R$ 66,66",
  },
  {
    id: 6,
    name: "Bermuda Fluminense Brasão Azul Marinho Foxton",
    src: "/lancamentos/bermuda-brasao-azul-marinho-64173-1.webp",
    price: "R$ 499,99",
    parcel: "ou 6x de R$ 83,33",
  },
  {
    id: 7,
    name: "Regata Fluminense Treino Menta/Laranja 2025 Umbro",
    src: "/lancamentos/regata-treino-menta-laranja-63348-1.webp",
    price: "R$ 219,99",
    parcel: "ou 4x de R$ 54,99",
  },
  {
    id: 8,
    name: "Camisa Fluminense Juvenil Treino Menta/Laranja 2025 Umbro",
    src: "/lancamentos/camisa-treino-verde-laranja-juvenil-63347-1.webp",
    price: "R$ 199,99",
    parcel: "ou 3x de R$ 66,66",
  },
  {
    id: 9,
    name: "Camisa Fluminense OF2 2025 Torcedor Umbro",
    src: "/lancamentos/camisa-of22025-torcedor-63327-1.jpg.webp",
    price: "R$ 369,99",
    parcel: "ou 6x de R$ 61,66",
  },
  {
    id: 10,
    name: "Camisa Fluminense Fem OF2 2025 Torcedora Umbro",
    src: "/lancamentos/camisa-of22025-torcedora-63332-1.jpg.webp",
    price: "R$ 319,99",
    parcel: "ou 6x de R$ 53,33",
  },
  {
    id: 11,
    name: "Camisa Fluminense Goleiro 2025 Preto/Verde Umbro",
    src: "/lancamentos/camisa-goleiro-adulto-preto-1.jpg.webp",
    price: "R$ 369,99",
    parcel: "ou 6x de R$ 61,66",
  },
  {
    id: 12,
    name: "Camisa Fluminense Goleiro 2025 Celeste/Marinho Umbro",
    src: "/lancamentos/camisa-goleiro-adulto-azul-1.jpg.webp",
    price: "R$ 369,99",
    parcel: "ou 6x de R$ 61,66",
  },
];
