export const linksCardMenu = [
  {
    menu: "Umbro",
    link: "#",
    submenu: [
      { menu: "Oficial 1", link: "#" },
      { menu: "Oficial 2", link: "#" },
      { menu: "Oficial 3", link: "#" },
      { menu: "Goleiro", link: "#" },
      { menu: "Treino", link: "#" },
      { menu: "Viagem", link: "#" },
      { menu: "Camisas", link: "#" },
      { menu: "Polos", link: "#" },
      { menu: "Regatas", link: "#" },
      { menu: "Jaquetas", link: "#" },
      { menu: "Shorts", link: "#" },
      { menu: "Calças", link: "#" },
    ],
  },
  {
    menu: "Masculino",
    link: "#",
    submenu: [
      { menu: "Camisa", link: "#" },
      { menu: "Regata", link: "#" },
      { menu: "Jaquetas", link: "#" },
      { menu: "Bermuda e Calção", link: "#" },
      { menu: "Calça", link: "#" },
      { menu: "Meias", link: "#" },
      { menu: "Outros", link: "#" },
    ],
  },
  {
    menu: "Feminino",
    link: "#",
    submenu: [
      { menu: "Camisa", link: "#" },
      { menu: "Croppeds", link: "#" },
      { menu: "Regata", link: "#" },
      { menu: "Jaquetas", link: "#" },
      { menu: "Vestido", link: "#" },
      { menu: "Fitness", link: "#" },
      { menu: "Shorts", link: "#" },
      { menu: "Meias", link: "#" },
      { menu: "Outros", link: "#" },
    ],
  },
  {
    menu: "Infantil",
    link: "#",
    submenu: [
      { menu: "Baby", link: "#" },
      { menu: "Infantil", link: "#" },
      { menu: "Juvenil", link: "#" },
      { menu: "Meias", link: "#" },
    ],
  },
  {
    menu: "Acessórios",
    link: "#",
    submenu: [
      { menu: "Alimentos e Bebidas", link: "#" },
      { menu: "Personalizáveis", link: "#" },
      { menu: "Garrafa e Squeeze", link: "#" },
      { menu: "Copos Colecionáveis", link: "#" },
      { menu: "Copo e Caneca", link: "#" },
      { menu: "Utensílio para Casa", link: "#" },
      { menu: "Joias", link: "#" },
      { menu: "Boné", link: "#" },
      { menu: "Bola", link: "#" },
      { menu: "Relógios", link: "#" },
      { menu: "Bandeiras e Flâmulas", link: "#" },
      { menu: "Papelaria", link: "#" },
      { menu: "Carteiras, Bags e Necessaires", link: "#" },
      { menu: "Bolsa e Mochila", link: "#" },
      { menu: "Chaveiro", link: "#" },
      { menu: "Óculos", link: "#" },
    ],
  },
  { menu: "Calçados", link: "#", submenu: [] },
  { menu: "Outlet", link: "#", submenu: [] },
];
