export const maisVendidosInfantilImgLink = [
  {
    name: "Camisa Fluminense Juvenil Brasão Verde 1A495A Starter",
    src: "/maisVendidosInfantil/camisa-juv-starter-brasao-verde-60942-1.webp",
    oldPrice: "",
    newPrice: "R$ 109,99",
    parcel: "ou 2x de R$ 54,99",
    discount: "",
  },
  {
    name: "Camisa Fluminense Juvenil OF1 2025 Umbro",
    src: "/maisVendidosInfantil/camisa-juvenil-of1-2025-63319-1.jpg.webp",
    oldPrice: "",
    newPrice: "R$ 299,99",
    parcel: "ou 5x de R$ 59,99",
    discount: "",
  },
  {
    name: "Agasalho Fluminense Inf Rain Braziline",
    src: "/maisVendidosInfantil/agasalho-infantil-fluminense-rain-60614-1.webp",
    oldPrice: "",
    newPrice: "R$ 139,99",
    parcel: "ou 2x de R$ 69,99",
    discount: "",
  },
  {
    name: "Chinelo Fluminense Inf Red Kids Flu DRF-01 Kenner",
    src: "/maisVendidosInfantil/chinelo-kenner-infantil-fluminense-dr1-60907-2.webp",
    oldPrice: "",
    newPrice: "R$ 119,99",
    parcel: "ou 2x de R$ 59,99",
    discount: "",
  },
  {
    name: "Camisa Fluminense Juvenil Brasão Grená 1A495A Starter",
    src: "/maisVendidosInfantil/camisa-juv-starter-brasao-grena-60943-1.webp",
    oldPrice: "",
    newPrice: "R$ 109,99",
    parcel: "ou 2x de R$ 54,99",
    discount: "",
  },
  {
    name: "Short Fluminense Juvenil OF2 2025 Umbro",
    src: "/maisVendidosInfantil/short-of22025-juvenil-63330-1.jpg.webp",
    oldPrice: "",
    newPrice: "R$ 199,99",
    parcel: "ou 3x de R$ 66,66",
    discount: "",
  },
  {
    name: "Camisa Fluminense Juvenil Goleiro 2025 Celeste/Marinho Umbro",
    src: "/maisVendidosInfantil/camisa-goleiro-juvenil-63316-1.jpg.webp",
    oldPrice: "",
    newPrice: "R$ 319,99",
    parcel: "ou 6x de R$ 53,33",
    discount: "",
  },
  {
    name: "Camisa Fluminense Juvenil Goleiro 2025 Roxo/Marinho Umbro",
    src: "/maisVendidosInfantil/camisa-goleiro-juvenil-63314-1.jpg.webp",
    oldPrice: "",
    newPrice: "R$ 319,99",
    parcel: "ou 6x de R$ 53,33",
    discount: "",
  },
  {
    name: "Camisa Fluminense Juvenil OF2 2025 Umbro",
    src: "/maisVendidosInfantil/camisa-of22025-juvenil-63328-1-1.jpg.webp",
    oldPrice: "",
    newPrice: "R$ 299,99",
    parcel: "ou 5x de R$ 59,99",
    discount: "",
  },
  {
    name: "Chinelo Fluminense Inf NK6 Kids Ampass DRH-01 Kenner",
    src: "/maisVendidosInfantil/chinelo-kenner-infantil-fluminense-drh01-60906-1.webp",
    oldPrice: "",
    newPrice: "R$ 139,99",
    parcel: "ou 2x de R$ 69,99",
    discount: "",
  },
  {
    name: "Camisa Fluminense Juvenil Fan Branca 1A496A Starter",
    src: "/maisVendidosInfantil/camisa-juvenil-starter-fan-branca-60944-1.webp",
    oldPrice: "",
    newPrice: "R$ 109,99",
    parcel: "ou 2x de R$ 54,99",
    discount: "",
  },
  {
    name: "Camisa Fluminense Juvenil Fan Grená 1A496A Starter",
    src: "/maisVendidosInfantil/camisa-juvenil-starter-fan-60945-1.webp",
    oldPrice: "",
    newPrice: "R$ 109,99",
    parcel: "ou 2x de R$ 54,99",
    discount: "",
  },
];
