export const maisVendidosFemininoImgLink = [
  {
    id: 13,
    name: "Camisa Fluminense Fem OF2 2025 Torcedora Umbro",
    src: "/maisVendidosFeminino/camisa-of22025-torcedora-63332-1.jpg.webp",
    oldPrice: "",
    newPrice: "R$ 319,99",
    parcel: "ou 6x de R$ 53,33",
    discount: "",
  },
  {
    id: 14,
    name: "Camisa Fluminense Fem OF1 2025 Torcedora Umbro",
    src: "/maisVendidosFeminino/camisa-torcedora-of1-2025-63321-1.jpg.webp",
    oldPrice: "",
    newPrice: "R$ 319,99",
    parcel: "ou 6x de R$ 53,33",
    discount: "-17%",
  },
  {
    id: 15,
    name: "Camisa Fluminense Fem OF1 2024 Jogadora Umbro",
    src: "/maisVendidosFeminino/camisa-fem-jogadora-of1-2024-1.webp",
    oldPrice: "R$ 399,99",
    newPrice: "R$ 329,99",
    parcel: "ou 6x de R$ 54,99",
    discount: "-37%",
  },
  {
    id: 16,
    name: "Camisa Fluminense Fem OF2 2024 Jogadora Umbro",
    src: "/maisVendidosFeminino/camisa-feminina-umbro-jg2-jogadora-1.webp",
    oldPrice: "R$ 399,99",
    newPrice: "R$ 249,90",
    parcel: "ou 4x de R$ 62,47",
    discount: "-17%",
  },
  {
    id: 17,
    name: "Canga Fluminense Blueman",
    src: "/maisVendidosFeminino/canga-fluminenses-branca-1.webp",
    oldPrice: "",
    newPrice: "R$ 239,99",
    parcel: "ou 4x de R$ 59,99",
    discount: "",
  },
  {
    id: 18,
    name: "Top Fluminense Cortininha Vies Flu02 Verde Blueman",
    src: "/maisVendidosFeminino/top-cortininha-vies-61673-1.jpg.webp",
    oldPrice: "",
    newPrice: "R$ 159,99",
    parcel: "ou 3x de R$ 53,33",
    discount: "",
  },
  {
    id: 19,
    name: "Calça Legging Fluminense Cós Recorte 02 Verde Blueman",
    src: "/maisVendidosFeminino/calca-legging-recorte-02-verde-blueman-61642-1.webp",
    oldPrice: "",
    newPrice: "R$ 239,99",
    parcel: "ou 4x de R$ 59,99",
    discount: "",
  },
  {
    id: 20,
    name: "Short Fluminense Recorte 02 Preto Blueman",
    src: "/maisVendidosFeminino/short-fluminense-recorte-02-preto-blueman-61643-1.webp",
    oldPrice: "",
    newPrice: "R$ 189,99",
    parcel: "ou 3x de R$ 63,33",
    discount: "-12%",
  },
  {
    id: 21,
    name: "Jaqueta Fluminense Fem Viagem 2024 Umbro",
    src: "/maisVendidosFeminino/jaqueta-feminina-viagem-umbro-2024-1.webp",
    oldPrice: "R$ 549,99",
    newPrice: "R$ 479,90",
    parcel: "ou 6x de R$ 79,98",
    discount: "-37%",
  },
  {
    id: 22,
    name: "Camisa Fluminense Feminina Atleta Jogo 2 Umbro 2023",
    src: "/maisVendidosFeminino/camisa-fluminense-feminina-atleta-jogo1-umbro-2023.webp",
    oldPrice: "R$ 399,90",
    newPrice: "R$ 249,90",
    parcel: "ou 4x de R$ 62,47",
    discount: "",
  },
  {
    id: 23,
    name: "Cropped Fluminense The Monst3r Is Back Beme",
    src: "/maisVendidosFeminino/cropped-tsilva-mockup-1.webp",
    oldPrice: "",
    newPrice: "R$ 99,99",
    parcel: "ou 2x de R$ 49,90",
    discount: "",
  },
  {
    id: 24,
    name: "Camisa Fluminense Feminina Quadrinhos Liga Retrô",
    src: "/maisVendidosFeminino/camisa-fluminense-feminina-quadrinhos-1.webp",
    oldPrice: "",
    newPrice: "R$ 139,90",
    parcel: "ou 2x de R$ 69,95",
    discount: "",
  },
];
